
```{r}
# Clean env
rm(list=ls())

# Load libs
library(tidyverse)
library(here)

# Load data
# data_outputs/coral_tidy_2024.csv
coral_df_tidy <- read_csv(here("data_outputs", "coral_tidy_2024.csv"))

# also grab
# data_outputs/coral_data_update_tidy_2024.csv
coral_df_update_tidy <- read_csv(here("data_outputs", "coral_data_update_tidy_2024.csv"))



```

```{r}

# Convert length, width, and height of the update df to be a str type
# this is because is because the current tidy data is treated as a string to presereve
# manually entered in Na values and UK values
coral_df_update_tidy <- coral_df_update_tidy %>% 
  mutate(
    length = as.character(length),
    width = as.character(width),
    height = as.character(height)
  )

# Bind the two together
coral_df_tidy_combined <- bind_rows(coral_df_tidy, coral_df_update_tidy)


```


```{r}
### DEBUG: Inspecting for duplicate rows
# let's see coral_number LTER4_OR_T03_Acr_0.75_0_0, except there's no coral number field, so we need to
# individually filter for all the fields
# coral_df_tidy_combined %>% filter(
#   site == "LTER4",
#   habitat == "OR",
#   transect == "T03",
#   taxa == "Acr",
#   x == 0.75,
#   y == 0,
#   z == 0
# )

# # Do same but for coral_df_tidy
# coral_df_tidy %>% filter(
#   site == "LTER4",
#   habitat == "OR",
#   transect == "T03",
#   taxa == "Acr",
#   x == 0.75,
#   y == 0,
#   z == 0
# )

## The bug is here -- coral_df_tidy ALREADY has the strange duplicate rows

# Do same but for coral_df_update_tidy
# coral_df_update_tidy %>% filter(
#   site == "LTER4",
#   habitat == "OR",
#   transect == "T03",
#   taxa == "Acr",
#   x == 0.75,
#   y == 0,
#   z == 0
# )
```



```{r}
# Save the combined data, overwriting the previous
# data_outputs/coral_tidy_2024.csv

write_csv(coral_df_tidy_combined, here("data_outputs", "coral_tidy_2024.csv"))

```

